echo [WARNING] en: YOU MUST HAVE INSTALLED PYTHON 3.7 TO USE THIS PROGRAM
echo [WARNING] it: E' NECESSARIO AVER INSTALLATO PYTHON 3.7 PER L'USO DI QUESTO PROGRAMMA
pip3 install --user -r requirements.txt
pip3 install -U telethon --user